# Generated by Django 4.2.5 on 2023-10-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambulatorio',
            options={'managed': False, 'verbose_name': 'Ambulatório', 'verbose_name_plural': 'Ambulatórios'},
        ),
        migrations.AlterModelOptions(
            name='atende',
            options={'managed': False, 'verbose_name': 'MedicoXConvênio', 'verbose_name_plural': 'MedicoXConvênios'},
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'managed': False, 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='convenio',
            options={'managed': False, 'verbose_name': 'Convênio', 'verbose_name_plural': 'Convênios'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'managed': False, 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'managed': False, 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='possui',
            options={'managed': False, 'verbose_name': 'Paciente|convênio', 'verbose_name_plural': 'Paciente|convênios'},
        ),
    ]
